4 New Elements!
l2wilson94/SandPond pull request #5
Opened 2021-05-01 23:53 UTC by ajawsome4ev

Plant Grows at a 50% chance charcoal burns very slowly generates lots of heat (great for grilling) and ash is burnt charcoal and is naturally warm

2021-05-02 14:10 UTC, l2wilson94 commented
The elements look great!

I think we should move the elements from the `CustomElements.js` file into one of the other files. Maybe `Sandbox.js`? We already have Glass element, so we'd just need to move the charcoals and ash. If you do that, I'd be happy to accept the pull request.

Thank you!

2021-05-02 19:48 UTC, ajawsome4ev commented
okay cool

2021-05-02 19:49 UTC, ajawsome4ev commented
the thing is that sandbox is getting very long and hard to read maybe a scroll bar is in order?
?

2021-05-02 20:19 UTC, ajawsome4ev commented
the thing is that sandbox is getting very long and hard to read maybe a scroll bar is in order?
?

2021-05-02 20:41 UTC, l2wilson94 commented
Great, thanks! And that's a good point! I've put an issue for fixing scroll, so I will try to fix that eventually. For the moment, I wonder if we should separate them into smaller categories. What do you think? I think Plant should go into the Life category probably.

Also, we still need to remove the elements from CustomElements.js so that it is nice and empty for people to try out the language if they want. Would you like to do it? Otherwise, I'd be happy to clean it up and accept the changes.

2021-05-02 22:45 UTC, ajawsome4ev commented
yeah i  will move plant into the life category and fix it i also cleared the custom elements

2021-05-02 22:45 UTC, ajawsome4ev commented
its done now

2021-05-03 10:16 UTC, ajawsome4ev commented
Fixed it finnally

2021-05-03 11:10 UTC, l2wilson94 requested changes
Almost there! :)

2021-05-03 11:10 UTC, l2wilson94 commented on Source/Elements/Sandbox.js
> +	emissive "2e362d"
This line is causing an error, it needs a '#' before the colour. Then I think it's good to go!

2021-05-03 11:37 UTC, l2wilson94 approved these changes

2021-05-03 11:38 UTC, merged

2021-05-03 11:38 UTC, l2wilson94 commented
Hooray!!